image: "alpine:3.12"

stages:
  - first
  - test
  
 first:
   stage: first
   script:
    - echo "First Task Started" >> firsttask.txt

test:
   stage: test
   script:
    - echo "Test Task Started" >> testtask.txt

