image: 'alpine:3.12'

stages:
  - test
  - publishtolocal
test:
   stage: test
   script:
    - echo "Test Task Started" >> testtask.txt
publishtolocal:
   stage: publishtolocal
   script:
    - apk update
    - apk add zip
    - apk add openssh-client
    - apk add sshpass
    - apk add git
    - apk add rsync
    #- wget https://github.com/gohugoio/hugo/releases/download/v0.92.2/hugo_extended_0.92.2_Linux-64bit.tar.gz
    #- tar -xvf hugo_extended_0.92.2_Linux-64bit.tar.gz
    #- mv hugo /usr/bin/
    - ls
    #- git clone "https://$GIT_USER:$GIT_PASS@git.csez.zohocorpin.com/BaaS/catalyst-docs.git"
    #- cd catalyst-docs/
    #- hugo version
    #- cd public/
    - sshpass -p "$LOCAL_PASS" ssh -o StrictHostKeyChecking=no "$LOCAL_USER_NAME"@"$LOCAL_SERVER" 'rm -rf ~/Documents/catalyst_visual/docs/hugo/catalyst-docs/*'
    - rsync -ratlz --rsh="/usr/bin/sshpass -p $LOCAL_PASS ssh -o StrictHostKeyChecking=no -l $LOCAL_USER_NAME" * "$LOCAL_SERVER":~/Documents/catalyst_visual/docs/hugo/catalyst-docs/
   only:
    - hugo-template-docs
