baseURL = "https://www.catalyst.zoho.com"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "catalyst"
theme = "catalyst"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup]
    defaultMarkdownHandler = "goldmark"
	
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.shortcuts]]
