baseURL = "https://www.catalyst.zoho.com"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "catalyst"
theme = "catalyst"



# To Render HTML Tag in Markdown files to set "unsafe = true"
[markup]
    defaultMarkdownHandler = "goldmark"
	
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.shortcuts]]
