# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "catalyst"
license = "MIT"
licenselink = "https://github.com/zoho/catalyst/blob/master/LICENSE.md"
description = "Documentation for zoho catalyst"
homepage = "https://github.com/zoho/catalyst"
repo = "https://github.com/zoho/catalyst"
tags = ["documentation", "menu","slide","search"]
features = ["documentation","menu","nested sections","search","slide", "attachments"]
min_version = 0.32

[author]
  name = "Dhinakar"

[original]
  name = "Learn"
  homepage = "https://matcornic.github.io/hugo-learn-doc/basics/what-is-this-hugo-theme/"
  repo = "https://github.com/matcornic/hugo-theme-learn"
  licenselink = "https://github.com/matcornic/hugo-theme-learn/blob/master/LICENSE.md"